steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/solodesign:latest
      - -t
      - gcr.io/$PROJECT_ID/solodesign:$SHORT_SHA
      - .

images:
  - gcr.io/$PROJECT_ID/solodesign:latest
  - gcr.io/$PROJECT_ID/solodesign:$SHORT_SHA
